version: '3'
services:
  api:
    build: .
    networks:
      - backend
    ports:
      - "3600:3600"
    depends_on:
      - mongo

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    networks:
      - backend
    ports:
      - "27017:27017"

  redis:
    image: redis
    networks:
      - backend
    ports:
      - "6379:6379"


networks:
  backend:
    driver: bridge